SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
PLAYER_RADIUS = 20
LINE_WIDTH = 2
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3
PLAYER_MAX_LIFES = 5
PLAYER_RESPAWN_INVINCIBILITY_SECONDS = 3.0

# Explosion visual effect settings
EXPLOSION_PARTICLE_COUNT = 18
EXPLOSION_PARTICLE_SPEED = 220
EXPLOSION_LIFETIME_SECONDS = 0.6
EXPLOSION_PARTICLE_RADIUS = 3
